export type AppLanguage = "ar" | "en";

const arToEn: Record<string, string> = {
  "مرج": "Marj", "مرج / إدارة": "Marj / Admin", "لوحة التحكم": "Admin", "نظرة عامة": "Overview", "المنتجات": "Products", "التصنيفات": "Categories", "السمات": "Attributes", "الطلبات": "Orders", "الشحن": "Shipping", "الدفع": "Payments", "التحليلات": "Analytics", "إعدادات المتجر": "Store settings", "العودة للمتجر": "Back to store", "ج.م": "EGP",
  "جرّبه عليك": "Try it on", "طلباتي": "My orders", "كل المنتجات": "All products", "تتبّع طلبك": "Track your order", "حسابي": "My account", "الشحن والاستبدال": "Shipping & returns", "المفضلة": "Wishlist", "السلة": "Cart", "إتمام الطلب": "Checkout", "اختر المحافظة وطريقة الدفع": "Choose governorate & payment", "الإجمالي الفرعي": "Subtotal", "الإجمالي قبل الشحن": "Total before shipping", "يُحدد حسب المحافظة": "Set by governorate", "متوفر": "Available", "نفدت الكمية": "Out of stock", "أضف للسلة": "Add to cart", "عرض المنتج": "View product",
  "كل القطع.": "Every piece.", "اختيارك أوضح.": "Choose with clarity.", "التصفية": "Filters", "بحث": "Search", "ترتيب": "Sort", "كل الحالات": "All statuses", "كل المخزون": "All inventory", "يحتاج متابعة": "Needs attention", "أضف منتجًا": "Add product", "لا توجد منتجات مطابقة": "No matching products", "جاري تحميل المنتجات...": "Loading products...", "قطعة منشورة": "published pieces", "قطعة مطابقة": "matching pieces", "إلغاء الكل": "Clear all", "التصنيف": "Category", "المقاس": "Size", "اللون": "Color", "السعر": "Price", "التوفر": "Availability",
  "إشارة حمراء": "Signal Red", "أبيض ورقي": "Paper White", "شبكة ليلية": "Night Grid", "رمادي خرسانة": "Concrete Grey", "أحمر إشارة": "Signal red", "أبيض ناصع": "Paper white", "أسود ليلي": "Night black", "رمادي فاتح": "Light concrete", "صورة المنتج قيد الرفع": "Product image coming soon",
  "هودي قطني ثقيل بقصة نظيفة وتفاصيل حمراء حادة.": "Heavy cotton hoodie with a clean cut and sharp red details.", "نسخة هادئة من الأساسيات، مصممة لتعيش مع كل إطلالة.": "A quiet essential designed to work with every look.", "أسود عميق مع طباعة شبكية صغيرة لمحبي التفاصيل الهادئة.": "Deep black with a small grid print for people who prefer subtle detail.", "توازن عملي بين الملمس الصناعي والراحة اليومية.": "A practical balance between industrial texture and everyday comfort.", "قطعة أساسية بلون لا يحتاج إلى شرح. صممنا إشارة حمراء من قطن ثقيل بملمس ناعم من الداخل، وقصة مريحة تحافظ على شكلها بعد يوم طويل.": "An essential in a color that needs no explanation. Signal Red uses heavyweight cotton with a soft inner feel and a relaxed cut that holds its shape through a long day.", "أبيض ورقي ليس أبيضًا عاديًا. درجة دافئة وقماش كثيف يجعلان القطعة أساسًا نظيفًا لكل طبقاتك اليومية.": "Paper White is not ordinary white. Its warm tone and dense fabric make it a clean foundation for everyday layers.", "تفصيلة صغيرة تغيّر كل شيء. شبكة حمراء دقيقة على أسود ليلي عميق، مع قماش يحافظ على حضوره بدون ضوضاء.": "A small detail changes everything: a precise red grid on deep night black, with fabric that keeps its presence without noise.", "رمادي محايد بقصة واسعة ومدروسة. قطعة سهلة، لكن ليست عادية؛ مناسبة للطبقات وللاستخدام اليومي المتكرر.": "A neutral grey with a considered relaxed cut. Easy but not ordinary, built for layering and repeated everyday use.",
  "الدفع عند الاستلام": "Cash on delivery", "Vodafone Cash": "Vodafone Cash", "InstaPay": "InstaPay", "بطاقة فيزا أو ائتمان": "Visa or credit card", "غير متصل": "Not connected", "موقوف": "Disabled", "ظاهر للعميل": "Visible to customer", "حفظ الطريقة": "Save method", "رسوم المحافظات": "Governorate fees", "ابحث عن محافظة": "Search governorate", "ملاحظة التوصيل": "Delivery note", "فعّال": "Enabled", "محافظة": "governorates",
  "طلبات تحتاج إجراء": "Orders needing action", "تنبيهات الـ variations": "Variation alerts", "مسودات تحتاج مراجعة": "Drafts to review", "المنتجات المنشورة": "Published products", "إجراءات سريعة": "Quick actions", "الكتالوج الحالي": "Current catalog", "المخزون": "Inventory", "الحالة": "Status", "العميل": "Customer", "التوصيل": "Delivery", "التاريخ": "Date", "جديد": "New", "تم التأكيد": "Confirmed", "قيد التجهيز": "Processing", "تم الشحن": "Shipped", "تم التسليم": "Delivered", "ملغي": "Cancelled",
  "ابدأ بما يحتاج قرارًا الآن: تنفيذ الطلبات، مخزون الـ variations، ثم الكتالوج.": "Start with what needs a decision now: order fulfillment, variation inventory, then the catalog.", "أنشئ منتجات حقيقية، أدِر أسعارها، وانشرها في الكتالوج.": "Create real products, manage their prices, and publish them in the catalog.", "راجع الطلبات الواردة وحدّث lifecycle التنفيذ من الجديد حتى التسليم.": "Review incoming orders and update their fulfillment lifecycle from new to delivered.", "لا توجد variations منخفضة المخزون وفق الحد الحالي.": "No variations are below the current stock threshold.", "لا توجد طلبات معلّقة أو قيد التجهيز الآن.": "There are no pending or processing orders right now.", "ابدأ صفحة منتج جديدة": "Start a new product page", "راجع المخزون": "Review inventory", "الـ variations التي تحتاج قرارًا": "Variations that need a decision", "تابع الطلبات": "Follow orders", "حدّث حالة التنفيذ والشحن": "Update fulfillment and shipping status", "تعتمد النظرة العامة على بيانات المنتجات والـ variations والطلبات الفعلية فقط. الإيراد، الدفع، التتبع، والإرجاع لا تظهر كمؤشرات قبل ربط مصادرها.": "The overview uses only real catalog, variation, and order data. Revenue, payment, tracking, and returns do not appear as metrics before their sources are connected.", "المعروض من قاعدة البيانات": "shown from the database", "لا يعني أن الطلب مدفوع": "does not mean the order is paid", "لا توجد طلبات ضمن هذا الفلتر.": "There are no orders under this filter.",
  "اختياراتك": "Your choices", "جاهزة.": "are ready.", "السلة لسه فاضية": "Your cart is empty", "اختار هودي من المجموعة، أو": "Choose a hoodie from the collection, or", "أولًا.": "first.", "استكشف المجموعة": "Explore the collection", "ملخص الطلب": "Order summary", "اختيار واضح": "A clear choice", "بدون تعقيد": "No complications", "تسجيل الخروج": "Sign out", "تسجيل الدخول للمتابعة": "Sign in to continue", "هذه الصفحة للمدير فقط": "This page is for admins only", "لا توجد طلبات بعد": "No orders yet", "لا توجد محافظة مطابقة للبحث.": "No matching governorate.",
  "الشحن والاستبدال.": "Shipping & returns.", "المعلومات المهمة": "Important information", "السياسات": "Policies", "إعدادات التشغيل": "Operating settings", "وسائل الدفع": "Payment methods", "كل الطلبات": "All orders", "قائمة الطلبات": "Order list", "قيمة الطلبات المسجلة": "Recorded order value", "متوسط الطلب المسجل": "Recorded average order", "طرق الدفع": "Payment methods", "المحافظات": "Governorates", "مقاييس ستظهر بعد الربط": "Metrics available after integration", "جاري تحميل الإعدادات...": "Loading settings...", "تعذر تحميل إعدادات المتجر حاليًا.": "Store settings are unavailable right now.", "الاستبدال والإرجاع": "Returns & exchanges", "اختر المحافظة وأتمم الطلب": "Choose governorate & checkout", "الشحن متاح لجميع محافظات مصر": "Shipping is available across Egypt", "راجع المقاس والكمية قبل إتمام الطلب.": "Review size and quantity before checkout.", "يظهر رسم الشحن النهائي بعد اختيار المحافظة في صفحة الإتمام.": "Final shipping is shown after selecting your governorate at checkout.",
  "ملابس يومية، بقرار واضح": "Everyday clothing, a clear choice", "الهودي": "The hoodie", "اللي عليك.": "that fits you.", "اختار القطعة. ارفع صورتك. شوفها عليك قبل ما تطلبها — مجانًا، وبخطوات بسيطة.": "Choose your piece. Upload your photo. See it on you before ordering — free and simple.", "استكشف المنتجات": "Explore products", "ابدأ التجربة المجانية": "Start the free try-on", "مش بنبيع شكل.": "We do not sell looks.", "بنصمم اختيار.": "We design a choice.", "اختار مزاجك.": "Choose your mood.", "شوفه عليك": "See it on you", "قبل القرار.": "before deciding.", "تجربة مجانية تساعدك تشوف القصة واللون على صورتك. بدون اشتراك، وبدون تعقيد.": "A free preview to see the fit and color on your photo. No subscription, no complexity.", "ارفع صورة واضحة": "Upload a clear photo", "صورتك": "Your photo", "الهودي المختار": "Selected hoodie", "ابدأ المعاينة": "Create preview", "خصوصيتك أولًا.": "Your privacy comes first.",
  "الفكرة": "The idea", "مرج مساحة لقطع يومية مستوحاة من البحر وحركة الموج. كل موديل له شخصية، وكل قرار شراء يبدأ من إنك تشوفه عليك فعلًا.": "Marj is a space for everyday pieces inspired by the sea and the movement of waves. Every design has a character, and every purchase starts by seeing it on you.", "المجموعة": "The collection", "أربع قطع. ألوان واضحة.": "Four pieces. Clear colors.", "ولا شيء زائد.": "Nothing extra.", "عرض كل المنتجات": "View all products", "التجربة الافتراضية": "Virtual try-on", "من الأمام، إضاءة جيدة، JPG / PNG / WebP": "Front-facing, good lighting, JPG / PNG / WebP", "لم يتم اختيار صورة بعد": "No photo selected yet", "حذف الصورة": "Remove photo", "تُرسل الصورة فقط لطلب إنشاء المعاينة ولا تُنشر في الكتالوج أو تُعرض لمستخدمين آخرين.": "Your photo is sent only to create the preview. It is not published in the catalog or shown to other users.", "تم اختيار القطعة من صفحة المنتج. ارفع صورتك فقط.": "This item was selected from its product page. Just upload your photo.", "غيّر القطعة": "Change item", "اختار هودي": "Choose a hoodie", "النتيجة": "Result", "اضغط لفتح الصورة": "Click to open image", "بنجهّز المعاينة...": "Preparing your preview...", "قد يستغرق الأمر لحظات": "This may take a moment", "المعاينة هتظهر هنا": "Your preview will appear here", "اختار صورة وابدأ": "Choose a photo to begin", "نزّل النتيجة": "Download result", "أوافق على معالجة صورتي مؤقتًا لإنشاء المعاينة.": "I agree to temporary processing of my photo to create the preview.", "جاري الإنشاء": "Creating preview", "جرّب مرة أخرى": "Try again", "ولّد المعاينة": "Generate preview", "تم إنشاء المعاينة بنجاح. اضغط على الصورة لفتحها بالحجم الكامل، أو نزّلها إذا احتجت.": "Preview created successfully. Click the image to open it full size, or download it if you need it.", "قطعة واضحة. وموجة أقرب لك.": "A clear piece. A wave closer to you.", "ارفع صورة بصيغة JPG أو PNG أو WebP فقط.": "Upload a JPG, PNG, or WebP image only.", "حجم الصورة كبير. استخدم صورة أقل من 6MB للحصول على تجربة أسرع.": "This image is too large. Use an image under 6MB for a faster experience.", "لم نتمكن من تجهيز الصورة. جرّب صورة أخرى.": "We could not prepare that image. Try another one.", "اختار صورة واضحة أولًا.": "Choose a clear photo first.", "لازم توافق على معالجة الصورة قبل البدء.": "You need to consent to photo processing before starting.", "تعذر قراءة الصورة": "Could not read the image", "تعذر تجهيز الصورة": "Could not prepare the image",
  "الكتالوج": "Catalog", "فلتر حسب اللون والمقاس والسعر والتوفر، ثم ادخل على القطعة أو جرّبها عليك مباشرة.": "Filter by color, size, price, and availability, then open an item or try it on directly.", "ابحث باسم القطعة أو اللون": "Search by item or color", "ابحث في المنتجات": "Search products", "مسح البحث": "Clear search", "الأحدث في الكتالوج": "Newest in catalog", "السعر: الأقل أولًا": "Price: low to high", "السعر: الأعلى أولًا": "Price: high to low", "فلاتر المنتجات": "Product filters", "أقل من ٩٠٠ ج.م": "Under 900 EGP", "٩٠٠ ج.م فأكثر": "900 EGP and above", "متوفر الآن": "Available now", "تعذر تحديث الكتالوج، نعرض البيانات المتاحة.": "Could not refresh the catalog; showing available data.", "لا توجد قطع مطابقة.": "No matching pieces.", "جرّب إزالة بعض الفلاتر أو ابحث بكلمة مختلفة.": "Try clearing some filters or searching with a different term.", "إلغاء كل الفلاتر": "Clear all filters", "اختار القطعة. شوفها عليك. قرر بوضوح.": "Choose your piece. See it on you. Decide clearly.",
  "غير موجود": "Not found", "القطعة دي مش موجودة.": "This item is not available.", "ارجع للكتالوج": "Back to catalog", "القصة": "Fit", "الخامة": "Fabric", "اختار المقاس": "Choose a size", "دليل المقاسات": "Size guide", "شوفه عليك مجانًا": "Try it on free", "محفوظ": "Saved", "تفاصيل القطعة": "Product details", "مصممة": "Designed", "للاستخدام.": "for everyday use.", "العناية:": "Care:", "قطع أخرى": "Other pieces", "كمّل المجموعة.": "Complete the collection.", "اسحب يمين / شمال لرؤية القطعة": "Drag left or right to view the piece", "صور العرض الحالية concept photography للتوضيح البصري. سيتم استبدالها بصور المنتج الفعلية عند اعتماد المخزون.": "Current display images are concept photography for visual reference. They will be replaced with real product images when inventory is approved.", "الواجهة الأمامية": "Front view", "الجهة الخلفية / الطباعة": "Back view / print", "زاوية إضافية": "Extra angle", "سيظهر عارض 3D هنا بمجرد رفع ملف GLB أو GLTF للمنتج من لوحة الإدارة.": "A 3D viewer will appear here when a GLB or GLTF file is uploaded from the admin panel.", "هذا المنتج يحتوي على رابط 3D غير مباشر. يجب أن يكون الملف بصيغة GLB أو GLTF، وليس صفحة متجر أو viewer.": "This product has an indirect 3D link. The file must be GLB or GLTF, not a store page or viewer.", "تعذر تحميل نموذج 3D. تأكد أن الملف GLB/GLTF عام وصالح، ثم أعد رفعه من لوحة الإدارة.": "Could not load the 3D model. Make sure the GLB/GLTF file is public and valid, then upload it again from the admin panel.", "حرّك المنتج وشوف التفاصيل": "Move the product and view the details", "تجربة Virtual Try-On مجانية — اختار صورتك وشوف القطعة قبل القرار.": "Free Virtual Try-On — choose your photo and see the piece before deciding.",
  "قطن عضوي 100%": "100% organic cotton", "قصة مريحة": "Relaxed fit", "جيب أمامي": "Front pocket", "تشطيب مطفي": "Matte finish", "غسيل بارد، مقلوبًا، وتجفيف طبيعي": "Cold wash inside out; air dry", "نسيج ناعم 420gsm": "Soft 420gsm fabric", "قصة unisex": "Unisex fit", "بطانة فرنسية": "French terry lining", "غسيل بارد مع ألوان مشابهة": "Cold wash with similar colors", "قطن ممشط": "Combed cotton", "طباعة مقاومة": "Durable print", "أساور مضلعة": "Ribbed cuffs", "غسيل مقلوب، بدون كي مباشر على الطباعة": "Wash inside out; do not iron directly on the print", "قصة واسعة": "Relaxed cut", "حياكة متينة": "Durable stitching", "غسيل بارد وتجفيف منخفض": "Cold wash; low tumble dry", "كمية محدودة": "Limited stock",
  "خامة قطنية ثقيلة": "Heavy cotton fabric", "خامة مختارة بعناية": "Carefully selected fabric", "تصميم مستقل من Marj": "Independent Marj design", "غسيل بارد وتجفيف طبيعي": "Cold wash and air dry", "مفضلة": "Save", "الرئيسية": "Home", "فتح ": "Open ", "إضافة ": "Add ", "إزالة ": "Remove ", "للمفضلة": "to wishlist", "من المفضلة": "from wishlist", "عناصر": "items", "صورة ": "Image ", "هودي ": "hoodie ",
  "هوديز": "Hoodies", "الاسم": "Name", "طلبك يبدأ من اختيار واضح": "Your order starts with a clear choice", "تقليل الكمية": "Decrease quantity", "زيادة الكمية": "Increase quantity", "حذف": "Remove", "تظهر وسائل الدفع بعد تفعيلها من الإدارة.": "Payment methods appear after they are enabled in admin.", "إتمام آمن وبسيط": "Simple, secure checkout", "بيانات التوصيل.": "Delivery details.", "اختر المحافظة وطريقة الدفع قبل تأكيد الطلب.": "Choose your governorate and payment method before confirming your order.", "بيانات العميل": "Customer details", "الاسم بالكامل": "Full name", "اكتب اسمك": "Enter your name", "رقم الهاتف": "Phone number", "عنوان التوصيل": "Delivery address", "المحافظة": "Governorate", "جاري تحميل المحافظات...": "Loading governorates...", "العنوان بالتفصيل": "Full address", "الشارع، رقم المبنى، الدور": "Street, building number, floor", "ملاحظات إضافية": "Additional notes", "اختياري": "Optional", "أي تفاصيل تساعدنا في التوصيل": "Any details that help with delivery", "طريقة الدفع": "Payment method", "جاري تحميل طرق الدفع...": "Loading payment methods...", "لا توجد طريقة دفع مفعلة حاليًا. راجع إدارة المتجر.": "No payment method is currently enabled. Please check store admin.", "الموافقة مطلوبة لإرسال الطلب.": "Consent is required to submit your order.", "تم تأكيد الموافقة.": "Consent confirmed.", "أوافق على استخدام بياناتي للتواصل بخصوص هذا الطلب فقط. لا يتم حفظ صور Virtual Try-On ضمن الطلب.": "I agree to the use of my details only to contact me about this order. Virtual Try-On images are not stored with the order.", "تأكيد الطلب": "Confirm order", "جاري تسجيل الطلب": "Submitting order", "مراجعة القطع": "Review items", "شحن مجاني": "Free shipping", "الشحن مجاني": "Shipping is free", "تم تطبيق حد الشحن المجاني من إعدادات المتجر.": "The free-shipping threshold from store settings has been applied.", "لا يمكن إتمام طلب بسلة فارغة": "You cannot check out with an empty cart", "العودة للسلة": "Back to cart", "تم استلام طلبك": "Your order was received", "شكرًا،": "Thank you,", "اختيارك اتسجل.": "your selection is recorded.", "رقم الطلب الخاص بك هو": "Your order number is", "هنتواصل معك لتأكيد التفاصيل قبل الشحن.": "We will contact you to confirm the details before shipping.", "العودة للمجموعة": "Back to collection", "تتبع الطلب لاحقًا": "Track your order later",
  "مفيش قطع محفوظة": "No saved pieces", "اضغط على القلب في أي منتج ليظهر هنا.": "Tap the heart on any product to see it here.", "احفظ القطع التي تريد الرجوع إليها.": "Save pieces you want to revisit.", "المفضلة محفوظة على هذا الجهاز.": "Wishlist items are stored on this device.", "مرج / المعلومات المهمة": "Marj / Important information", "والاستبدال.": "and returns.", "نوضح لك طريقة وصول طلبك وما تحتاج معرفته قبل الإتمام.": "We explain how your order arrives and what you need to know before checkout.", "SHIPPING / مصر": "SHIPPING / EGYPT", "الشحن مجاني للطلبات من": "Shipping is free for orders from", "رسوم الشحن تُعرض عند إتمام الطلب.": "Shipping fees are shown at checkout.", "متابعة الطلب": "Track order", "أين وصل": "Where is", "طلبك؟": "your order?", "اكتب رقم الطلب والبريد المستخدم": "Enter the order number and email used", "عند إتمام الشراء.": "at checkout.", "رقم الطلب": "Order number", "البريد الإلكتروني": "Email address", "جاري البحث...": "Searching...", "ابحث عن الطلب": "Find order", "استلمنا الطلب": "Order received", "أكدنا التفاصيل": "Details confirmed", "بنجهز طلبك": "Preparing your order", "خرج للتوصيل": "Out for delivery", "الحالة الحالية لا تعني إتمام الدفع؛ الدفع عند الاستلام ويتم تأكيده هاتفيًا قبل الشحن.": "The current status does not mean payment is complete; cash on delivery is confirmed by phone before shipping.", "بعد تسجيل الطلب، ستجد رقم المتابعة في شاشة التأكيد.": "After submitting your order, you will find the tracking number on the confirmation screen.",
  "تحدد تكلفة ومدة الشحن من لوحة الإدارة قبل تفعيل الإطلاق.": "Shipping cost and delivery time are set in store admin before launch.", "تُحرَّر سياسة الاستبدال والإرجاع من لوحة الإدارة قبل الإطلاق.": "The returns and exchanges policy is edited in store admin before launch.", "يمكن عرض وسائل الدفع بعد ربطها من لوحة الإدارة.": "Payment methods can be displayed after they are configured in store admin.",
  "تحبّها.": "you love.", "سجّل الدخول لمتابعة طلباتك وبيانات حسابك.": "Sign in to view your orders and account details.", "تسجيل الدخول": "Sign in", "الإدارة": "Admin", "لوحة الإدارة مخصصة للحسابات المصرح لها بإدارة المنتجات والطلبات والمخزون.": "The admin area is reserved for authorized accounts that manage products, orders, and inventory.",
  "جاري تحميل الحساب...": "Loading account...",
  "النمو والتشغيل": "Growth & operations", "خصومات حقيقية، مراجعات مشترين موثقة، تعديل مخزون يدوي، وLookbook من محتوى تضيفه أنت فقط.": "Real discounts, verified buyer reviews, manual inventory adjustments, and a Lookbook you publish yourself.", "كوبون جديد": "New coupon", "الكود": "Code", "نوع الخصم": "Discount type", "نسبة مئوية": "Percentage", "قيمة ثابتة": "Fixed amount", "القيمة": "Value", "حد أدنى للسلة": "Minimum cart total", "عدد الاستخدامات (اختياري)": "Usage limit (optional)", "يبدأ في": "Starts on", "ينتهي في (اختياري)": "Ends on (optional)", "مفعّل للعملاء": "Enabled for customers", "إنشاء الكوبون": "Create coupon", "استخدم": "Used", "إيقاف": "Disable", "تفعيل": "Enable", "مراجعات تنتظر القرار": "Reviews awaiting a decision", "لا توجد مراجعات. لا ينشئ المتجر مراجعات أو تقييمات تجريبية.": "There are no reviews. The store never creates sample reviews or ratings.", "نشر": "Publish", "رفض": "Reject", "تعديل مخزون Variation": "Variation stock adjustment", "استخدم رقم الـvariation من شاشة المنتج؛ يسجل النظام السبب والرصيد الناتج ولا يسمح برصيد سالب.": "Use the variation ID from the product page; the system records the reason and resulting balance and never allows negative stock.", "رقم Variation": "Variation ID", "التغيير (+ أو -)": "Change (+ or −)", "سبب التعديل": "Adjustment reason", "تسجيل التعديل": "Record adjustment", "لا توجد تعديلات مسجلة.": "No adjustments have been recorded.", "إضافة محتوى Lookbook": "Add Lookbook content", "أضف صورًا تملك حق استخدامها فقط. لا ينشئ المتجر صورًا أو قصص عملاء من تلقاء نفسه.": "Only add images you have the right to use. The store does not fabricate images or customer stories.", "العنوان بالعربية": "Arabic title", "العنوان بالإنجليزية": "English title", "رابط الصورة المباشر": "Direct image URL", "معرّف المنتج (اختياري)": "Product ID (optional)", "الترتيب": "Sort order", "نشر للعملاء": "Publish for customers", "وصف اختياري": "Optional description", "إضافة المدخلة": "Add entry", "لا توجد مدخلات Lookbook بعد.": "No Lookbook entries yet.", "خصمك ونقاطك": "Your discounts & points", "كود الخصم": "Discount code", "جاري التحقق...": "Checking…", "الكود غير صالح": "The code is not valid", "كل نقطة = 1 ج.م خصم. تُمنح النقاط بعد تسليم الطلب.": "Each point equals 1 EGP off. Points are earned after delivery.", "سجّل الدخول لاستخدام نقاط الولاء وحفظ المفضلة في حسابك.": "Sign in to use loyalty points and save favorites to your account.",
};

const enToAr = Object.fromEntries(Object.entries(arToEn).map(([ar, en]) => [en, ar]));

function replaceAll(value: string, replacements: Record<string, string>) {
  return Object.entries(replacements)
    .sort(([a], [b]) => b.length - a.length)
    .reduce((result, [from, to]) => result.replaceAll(from, to), value);
}

export function translateVisibleText(value: string, language: AppLanguage) {
  return language === "en" ? replaceAll(value, arToEn) : replaceAll(value, enToAr);
}

export function languageDirection(language: AppLanguage) {
  return language === "ar" ? "rtl" : "ltr";
}

export function languageLabel(language: AppLanguage) {
  return language === "ar" ? "English" : "العربية";
}
